### ISSUE TITLE
Tests don't run properly

### ISSUE THREAD

**Issue by nibrahim** [suroorhussain/Hoso#7]
After installing the `facebook` module (#6), I run tests and see this

    =============================================================== test session starts ===============================================================
    platform linux2 -- Python 2.7.9, pytest-2.8.3, py-1.4.31, pluggy-0.3.1
    rootdir: /tmp/Hoso, inifile: 
    plugins: cov-2.2.0
    collected 1 items 

    test_channels.py F

    ==================================================================== FAILURES =====================================================================
    _____________________________________________________________ test_facebook_broadcast _____________________________________________________________

        def test_facebook_broadcast():
            access_token = """CAACEdEose0cBAH8DfFEcTzrYXrdBlsPwJZBwqjZBqZAHyjDBViaZANLPHs3xXEeE91uyww5MZAcuLoA2dzGmqwo49ubUd7VHPbMcmjMlmieBXYv9AOfU5D6bCeCnLUILCEktevMnyiELHZAQcbE1zKXVkjKZA3oFgV1F7YU49eB5ZAGF1TqwbEgK4w0qQIIeCMWf3mylueh7VQZDZD"""
    >       graph = facebook.GraphAPI(access_token)
    E       AttributeError: 'module' object has no attribute 'GraphAPI'

    test_channels.py:6: AttributeError
    ============================================================ 1 failed in 0.01 seconds =============================================================

So, your setup is not yet clear. Please fix it.

**Comment by suroorhussain** [comment]
a setup has been added. Please Reopen if this doesn't solve the issue

**Comment by nibrahim** [comment]
Doesn't work. Please verify again. Also, I'm sending an email directly to the list about this.
